### ISSUE TITLE
[BUG] Pressing right mouse button while dragging with left causes box to disappear

### ISSUE THREAD

**Issue by EmoCthulhu** [dovrosenberg/foundry-simple-weather#28]
Somehow, when I was trying to position Simple Weather at the top left of my screen I accidentally hit right click at the same time, and the box shot off to the left at high speed. Moving the canvas as far as it will go in any direction doesn't find it. A button to reset position would be wonderful. I have been unable to reproduce this on my local Foundry, it happened on a Forge hosted system (Dragonbane). I haven't wanted to try to reproduce it on any other game, as then I won't have Simple Weather for those games either! So I'm suffering with Weather Control for now on Dragonbane, but would love Simple Weather back.

OK to reproduce this: Local Foundry, simply right click on the Calendar box. After that all games will not show the Calendar box. Forge hosted, right click while dragging. This will only make it disappear on the game that you did this on. 

 - OS: Windows 11
 - Browser Chrome and Edge
 - Version Foundry V11 Build 313

Note: I have tried uninstalling/reinstalling, uninstalling and then pulling my Foundry version into the Forge as a custom module, but no matter what it remembers the position, wherever that is.

**Comment by dovrosenberg** [comment]
I will look into this ASAP, though at first glance, I can't reproduce it.  Any particular place in the calendar box you're clicking?

You can get your Simple Weather back in the meantime by going into the Chrome/Edge debugger console and entering:

`game.settings.set('simple-weather', 'windowPosition', { bottom: 400, left: 100})`

Then refresh the browser.  If those instructions don't make sense, let me know, and I'll give more clear ones - not sure your level of technical proficiency.

**Comment by EmoCthulhu** [comment]
I'm clicking the top bar where the cursor changes to show you can move it.
Doesn't do it on the open weather box, just the calendar. It may have to
already be in motion when it happens.

My level of technical proficiency is I know exactly how to do what you
said, but wouldn't have known to try that. When I get home I'll be so happy
to have it back.

Thanks!

**Comment by dovrosenberg** [comment]
You'd have no reason to know. It stores the location in a hidden setting (module-specific), so that code will overwrite the setting and then reposition it when it reloads after the refresh. Let me know if you have trouble.

**Comment by EmoCthulhu** [comment]
Ok, just got it back on my local Foundry, and yes it already has to be in
motion before you accidentally right click, at which point it goes zooming
off to the left again.

My apologies for saying that all you have to do is right click.

You'd certainly have no reason to expect a player having a low blood sugar
issue would tremble and accidentally right click while dragging an
element...

**Comment by dovrosenberg** [comment]
Fixed in v1.5.3

**Comment by EmoCthulhu** [comment]
Ok, worked in one game hosted on the Forge, then I noticed you'd updated
already to fix the issue, so I updated, tested on local Foundry, and when I
went to do my next game on the Forge, I get this error in the Console after
inputting your code (so it's still missing on the second game):

foundry.js:3322 Uncaught (in promise) Error: This is not a registered game
setting
    at ClientSettings.set (foundry.js:3322:42)
    at <anonymous>:1:15

One other thing I've noticed, is that my set up is to have "Open on Load"
unchecked in Simple Calendar, and then Simple Weather doesn't appear until
Simple Calendar is opened. Wasn't sure if that was by design or not.

**Comment by EmoCthulhu** [comment]
Um never mind, I didn't have the module on (sneaks away embarrassed).
